pool:
  vmImage: 'ubuntu-16.04'
variables: # pipeline-level
  BUILD_ENV: 'PROD'

steps:
- script: echo initializing...
  displayName: 'Initializing...'
- script: sudo npm install -g @angular/cli@11.2.7 > /dev/null

- script: sudo mkdir -p appRoot
- script: cd appRoot && sudo ng new angular-demo --defaults
- script: sudo cp -r angular-demo/. appRoot/angular-demo
- script: cd appRoot/angular-demo && sudo npm install --${BUILD_ENV} > /dev/null
- script: cd appRoot/angular-demo && sudo npm run setup
- script: echo building...
- script: cd appRoot/angular-demo && sudo ng build #--base-href /angular-demo/

