version: "3.9"

services:
  db:
    image:mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: letmein2
    ports:
      - "27017:27017"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  platform:
    image: theharbormaster/angular-demo:latest
    ports:
      - "4200:4200"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: letmein2
    depends_on:
      - db
    links:
      - db

